"""Run env experiment """
from argparse import ArgumentParser

from intmcp.run import exp as exp_lib


if __name__ == "__main__":
    parser = ArgumentParser()
    parser.add_argument(
        "yaml_path", type=str,
        help="Experiment YAML File path"
    )
    parser.add_argument(
        "--n_procs", type=int, default=None,
        help="Number procs to use (default=None=see config)"
    )
    parser.add_argument(
        "--test_run", action='store_true',
        help="Do test run (generates and displays exp params)"
    )
    parser.add_argument(
        "--extra_output_dir", type=str, default=None,
        help=("An optional directory to save compiled results too, in addition"
              " to autogenerated results dir")
    )
    parser.add_argument(
        "-l", "--log_level", type=int, default=exp_lib.EXP_LOG_LEVEL,
        help="Logging level for stdout (default=logging.INFO+1)"
    )
    args = parser.parse_args()

    exp_lib.run_yaml_experiment(**vars(args))
